apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zen-lead-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zen-lead-role
subjects:
- kind: ServiceAccount
  name: zen-lead-controller-manager
  namespace: zen-system

