apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zen-lead-role
rules:
- apiGroups: ["coordination.kube-zen.io"]
  resources: ["leaderpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.kube-zen.io"]
  resources: ["leaderpolicies/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["coordination.kube-zen.io"]
  resources: ["leaderpolicies/finalizers"]
  verbs: ["update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

